# Generated by Django 2.0.3 on 2018-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('shortid', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('orginalurl', models.URLField()),
            ],
        ),
    ]
